name: idle_rpg
description: Idle RPG Flutter client.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.3

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  game_core: ^0.1.0
  idle_rpg_client:
    path: ../server_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
